name: GPT Code Review on Pull Request

on:
  pull_request:
    branches:
      - main                  # You can specify other branches where pull requests will trigger the workflow
    types: [opened, synchronize]  # Run the workflow when a PR is created or updated

jobs:
  gpt_code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3    # Step 1: Checkout the PR code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'      # Step 2: Set up Python 3.x environment

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai          # Step 3: Install OpenAI SDK for Python

      - name: Read code and trigger GPT review
        run: |
          python code_review.py       # Step 4: Run your Python script

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Step 5: Securely provide the OpenAI API key
