name: GPT Code Review on Push or Pull Request

on:
  push:
    branches:
      - '*'                   # Trigger on any push to any branch
  pull_request:
    branches:
      - '*'                   # Trigger on any pull request to any branch

jobs:
  gpt_code_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is cloned

      - name: Clean workspace
        run: git clean -fdx  # Clean workspace to avoid leftover files

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Run GPT code review
        run: |
          python .github/workflows/script.py

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
