name: GPT Code Review on Pull Request

# This section defines when the workflow is triggered
on:
  pull_request:
    branches:
      - '*'                        # Use a wildcard to trigger the workflow on any branch
    types: [opened, synchronize]    # Triggers when a PR is created or updated

jobs:
  gpt_code_review:
    runs-on: ubuntu-latest          # Runs on the latest Ubuntu environment

    steps:
      # Step 1: Checkout the code in the pull request
      - name: Checkout repository code
        uses: actions/checkout@v3

      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'     # Specify the Python version to use

      # Step 3: Install necessary dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      # Step 4: Run the Python script for GPT review
      - name: Run GPT code review
        run: |
          python .github/workflows/script.py  # Ensure the correct path to the script

    # Step 5: Securely use the OpenAI API key stored in GitHub Secrets
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

